stackbuilders/hapistrano

.travis.yml, hapistrano.cabal, src/System/Hapistrano.hs
@sestrella @jsantos17 do you have any comments?
=> Add ghc 7 10 support

app/Main.hs, hapistrano.cabal, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs
=> Clean up (Cabal) package

.travis.yml, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs
=> Fix tests on Linux

.travis.yml, spec/System/HapistranoSpec.hs
=> Fix Git configuration for tests

app/Main.hs
=> Handle command line options with GetOpt

.travis.yml
=> Update travis.yml to works with stack

app/Command.hs, app/Flag.hs, app/Main.hs, app/Options.hs, hapistrano.cabal, stack.yaml
Sorry, for taking too long. It's the first time I use this library.
@jpvillaisaza Could you tell me please if I'm in the right way? Thanks in advance.
=> Add optparse-applicative for parsing args

script/clean-build.sh, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs
@jpvillaisaza @sestrella could you take a look please?
=> Support comments and empty lines, solves #41

app/Main.hs, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs, src/System/Hapistrano/Commands.hs
=> Add verification before rollbacks

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, hapistrano.cabal, src/System/Hapistrano.hs
=> Use ‘hap.yaml’ to store configuration

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, hapistrano.cabal, spec/System/HapistranoSpec.hs, src/System/Hapistrano/Core.hs, src/System/Hapistrano/Types.hs
=> Implement concurrent multihost deployment

app/Main.hs
The old way of seeing the version of the program was by doing
something like this:
hap deploy -v
This patch makes it viewable by doing like this (which I feel is a
proper way to do):
hap -v
=> Fix version display

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, src/System/Hapistrano.hs
Fixes #65 
I have documented on the README.md on how to use this parameter. Let me know if you need any clarifications.
=> Add ability to make version control related activities optional

CHANGELOG.md, hapistrano.cabal, src/System/Hapistrano.hs
This fixes: https://github.com/stackbuilders/hapistrano/issues/73
=> Loose constraint for `path-io`

CHANGELOG.md, hapistrano.cabal, stack.yaml
This fixes https://github.com/fpco/stackage/issues/3268
=> Loose bounds for async to < 2.4

.dockerignore, .travis.yml, Dockerfile, deploy.sh, hapistrano.cabal
Implements:
* Dockerfile for building Hapistrano
TODO:
* Done from Docker Hub
* Done from Docker Hub
Acceptance criteria:
* The image is public and can be used in CI for deploying applications.
=> Docker image

CHANGELOG.md, Dockerfile, README.md, hapistrano.cabal
And update README.md and CHANGELOG.md
=> Create ~/.ssh directory on the Docker image.

CHANGELOG.md, hapistrano.cabal, stack.yaml
See https://github.com/commercialhaskell/stackage/issues/4053
=> Loose bound for yaml-0.11

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, hapistrano.cabal, spec/System/HapistranoSpec.hs, src/System/Hapistrano/Types.hs
Co-authored-by: Esteban Ibarra <eibarra1992@hotmail.com>
=> [Closes #105] Read `release-format` and `keep-releases` from the configuration file

.travis.yml, CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, hapistrano.cabal, spec/System/HapistranoSpec.hs, src/System/Hapistrano/Commands.hs, src/System/Hapistrano/Core.hs, src/System/Hapistrano/Types.hs
Solves #84 
---
@juanpaucar Could you take a look please?
=> Support for zsh default shell fails

.travis.yml, CHANGELOG.md, hapistrano.cabal, spec/System/HapistranoSpec.hs, src/System/Hapistrano/Core.hs
Adding timestamp when performing an action
=> added timestamp

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, hapistrano.cabal, src/System/Hapistrano/Core.hs, src/System/Hapistrano/Types.hs, stack.yaml.lock
To solve #120 
```yml
deploy_path: '/tmp/my-project'
host: localhost
port: 22
ssh_args:
- "-v"
repo: 'https://github.com/stackbuilders/hapistrano.git'
revision: origin/master
build_script:
- stack setup
- stack build
restart_command: echo "FINISHED!"`
```
=> Add SSH args

CHANGELOG.md, hapistrano.cabal, src/System/Hapistrano/Core.hs
Closes #119 
~~BTW, you can check the output of the CI also~~.
You actually can't :rofl: the CI only runs the tests, doesn't show the output of them
=> Colorize output

CHANGELOG.md, Dockerfile, hapistrano.cabal
I removed the testing packages for the Docker file build.
=> Remove testing dependencies of the Dockerfile

CHANGELOG.md, hapistrano.cabal, spec/System/HapistranoSpec.hs, stack.yaml, stack.yaml.lock
=> Add support for LTS-15.0

CHANGELOG.md, README.md, app/Config.hs, app/Main.hs, fixtures/git_repository_config.yaml, fixtures/local_directory_config.yaml, hapistrano.cabal, spec/System/HapistranoConfigSpec.hs, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs, src/System/Hapistrano/Config.hs, src/System/Hapistrano/Types.hs
A proposal for closing #116.
If this makes sense, could you let me know @juanpaucar, so I can carry on with some tests for backward compatibility and updating the documentation :smile:
=> Copy directory instead of cloning an entire repository

CHANGELOG.md, hapistrano.cabal, stack.yaml, stack.yaml.lock
This solves:
https://github.com/commercialhaskell/stackage/issues/5592
=> Allow ansi-terminal-0.11

.travis.yml, CHANGELOG.md, app/Main.hs, default.nix, hapistrano.cabal, stack.yaml, stack.yaml.lock
This solves our part on https://github.com/commercialhaskell/stackage/issues/5686
I'm disabling osx from the testing matrix until we can figure out why it is failing to find those packages on brew. Locally, I can find both packages on brew and they seem to be available: [ghc](https://formulae.brew.sh/formula/ghc) and [cabal](https://formulae.brew.sh/formula/cabal-install). The [error](https://travis-ci.org/github/stackbuilders/hapistrano/jobs/763046417) seems to tell us that it can't find the packages. This will need further investigation. I'll open a separate issue for that.
=> Loose constraint for formatting

.travis.yml
Closes #152 
Thanks, @mauriciofierrom for the help
=> Reenable macOS with XCode12

CHANGELOG.md, Dockerfile, default.nix, hapistrano.cabal
=> Allow aeson 2

default.nix
=> Fix for Nix's "error: attribute 'lib' missing"

.github/workflows/build-and-test.yml
Let's try this, since this way we can get more information about what's happening during this step and will make debugging failing Haddock buillds easier (if it works).
=> Changed command at the Haddock step

.github/workflows/ci.yml, .github/workflows/docker.yml, README.md
=> [#188] Push image to a Docker registry

.github/workflows/docker.yml, Dockerfile
=> [#133] Create releases with pre-compiled binaries

CHANGELOG.md, README.md, default.nix, hapistrano.cabal
Changes:
- Update README.md
- Update version
=> [Release] v0.4.6.0

hapistrano.cabal, src/System/Hapistrano.hs
=> check if the path exists before rollback to a specific release.

src/System/Hapistrano.hs
Include release path in error message.
=> chore: Change error message

.github/workflows/build.yml, README.md, spec/System/HapistranoSpec.hs
Updating some CI stuff:
* Fix cache of cabal packages. Now, it's much bigger:
* Before: https://github.com/stackbuilders/hapistrano/actions/runs/3474036802/jobs/5806744212#step:8:11
* Now: https://github.com/stackbuilders/hapistrano/actions/runs/3700436874/jobs/6268855978#step:8:13
=> chore: Update CI

hapistrano.cabal, spec/System/HapistranoConfigSpec.hs, src/System/Hapistrano/Config.hs
I noticed we had a wrong filter for unique targets that was getting only the
first target. I fixed that so it can take all unique hosts.
=> fix: Filter for multiple targets

CHANGELOG.md, default.nix, hapistrano.cabal
- Update version in hapistrano.cabal
- Update Changelog
=> bump version 0.4.7.0

hapistrano.cabal
=> misc: Update cabal documentation

src/System/Hapistrano.hs
- fix: Change where validation occurs
=> fix: Error on release path activation

CHANGELOG.md, README.md, app/Main.hs, hapistrano.cabal, spec/System/Hapistrano/ConfigSpec.hs, spec/System/HapistranoConfigSpec.hs, spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs, src/System/Hapistrano/Config.hs
=> Add support for lead target commands

.all-contributorsrc, .github/workflows/build.yml, README.md
-  Add @juanpaucar as a contributor
-  Add @jsl as a contributor
-  Add @DavidMazarro as a contributor
-  Add @sestrella as a contributor
-  Add @mrkkrp as a contributor
-  Add @jpvillaisaza as a contributor
-  Add @CristhianMotoche as a contributor
-  Add @psibi as a contributor
-  Add @ibarrae as a contributor
-  Add @cptrodolfox as a contributor
-  Add @goetzc as a contributor
-  Add @javcasas as a contributor
-  Add @darthdeus as a contributor
-  Add @nickovivar as a contributor
-  Add @felixminom as a contributor
-  Add @elcuy as a contributor
-  Add @fefi95 as a contributor
-  Add @alexisbcc as a contributor
-  Add @GioDavid as a contributor
-  Add @FranzGB as a contributor
-  Add @hughjfchen as a contributor
-  Add @boceto1 as a contributor
-  Add @ng29 as a contributor
-  Add …
=> chore: Add All Contributors

spec/System/HapistranoSpec.hs, src/System/Hapistrano.hs, src/System/Hapistrano/Types.hs
Hi, this PR applies the following changes:
- Hlint suggestions
- Spelling mistakes
Hope this helps!
=> Lint and grammar fixes

.github/workflows/build.yml
Allowing the build workflow to run when a PR is opened.
=> Run build workflow on PR
