stackbuilders/hapistrano

app/Main.hs
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Types.hs

I lookup the environmental variable `PORT` to deploy the application to a different ssh port if it is present. If it is not, then we take the default port. So, the variable `PORT` is optional. To solve #35

Parse env variable PORT

---

.travis.yml
app/Command.hs
app/Flag.hs
app/Options.hs
hapistrano.cabal
src/System/Hapistrano.hs
src/System/Hapistrano/Types.hs

We should test with Cabal, not stack, because it allows to test in more adverse environment, test with GHC versions that are not yet in snapshorts, and generally improve compatibility.
This script tests with Cabal 1.24, as it's compatible with all GHC versions of interest and has a better dependency resolution algorithm that allows to avoid some problems with builds.
I also would like to impose 100% Haddock coverage here.

Use a different Travis script

---

README.md
app/Config.hs
app/Main.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Core.hs

Close #54. In this version we just allow to copy arbitrary files and directories specified in the configuration. Copying should be quite fast and it's more straightforward than linking across releases, which is probably language-dependent solution (i.e. we know that we want to link `.stack-work`, but with other languages maybe we would want to copy just binary file). In any case the solution implemented here seems to be more general to me.

Allow copy precompiled files

---

CHANGELOG.md
app/Main.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Core.hs

This PR fixes a few issues I faced when I was playing with the new Hapistrano. With these fixes I find the tool quite usable and ready for switching to.
There are also important points about it I'd like to document:
* Changing environment in build script won't work because commands are executed one by one. Solution is to use `&&` to chain `export` and target command to get a single command, like this:
```yaml
build_script:
- mkdir -p log/
- touch log/access.log
- touch log/error.log
- export DBM_DATABASE="dbname=clearnexus_staging" && export DBM_DATABASE_TYPE=postgresql && export DBM_MIGRATION_STORE=migrations && ~/.local/bin/moo upgrade
```
* We should not really copy entire `.stack-work` directory for two reasons: 1) it doesn't seem to work, I get an error about missing files referring …

Fix some issues

---

app/Main.hs

This would make optparse-applicative automatically generate help for subcommands.
Previous behaviour:
```bash
$ hap deplo --help
Hapistrano - A deployment library for Haskell applications
Usage: hap [-v|--version] COMMAND [-c|--config PATH]
Deploy tool for Haskell applications
Available options:
-h,--help                Show this help text
-v,--version             Show version of the program
-c,--config PATH         Configuration file to use (default: "hap.yaml")
Available commands:
deploy                   Deploy a new release
rollback                 Roll back to Nth previous release
```
New behavior: 
```bash
$ hap deploy --help
Usage: hap deploy [-r|--release-format ARG] [-k|--keep-releases ARG]
Deploy a new release
Available options:
-r,--release-format ARG  Which format release …
```

Generate help for subcommands

---

.travis.yml
CHANGELOG.md
hapistrano.cabal
stack.yaml

In order to re-add hapistrano to stackage some more constraints have to be relaxed
https://github.com/fpco/stackage/pull/2736
As travis shows:
https://travis-ci.org/fpco/stackage/builds/262422809

Loose package constraints

---

README.md
app/Config.hs
app/Main.hs
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs

I have changed the section name to `run_locally` (from `local_command` in the initial proposal in https://github.com/stackbuilders/hapistrano/issues/81) so that it sort of resembles closely to Capistrano.
Thanks @jsl for pointing out the relevant Capistrano documentation.

Implement feature to run local commands

---

CHANGELOG.md
hapistrano.cabal

This fixes #79 
it is not possible to support versions older than 7.10 since there were  some api changes

Correct boundaries for old base package

---

spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Commands.hs

Based on the discussion on #67 and #69, this changes the default behavior to set the release to the correct revision by checking out a branch or a commit instead of using git reset.

Use git checkout to set the release revision (close #69)

---

.travis.yml
CHANGELOG.md
README.md
app/Config.hs
app/Main.hs
hapistrano.cabal
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Types.hs

Solves #63 
As the issue mentions, some flags are not supported by those UNIX systems which are not Linux. This means that for `mv` and `ln` we can't use `-T` as an argument; and for `readlink` we can't use `-f` in the way we've been doing it.
On this PR, I introduce a new optional key to make explicit the target platform where Hapistrano will deploy. By default, it would asume it's GNU/Linux. On the other hand is explicitly stated, it will now be able to read `linux`, `windows` and any other option will be taken as a BSD system

Add support for deployment on non-GNU/Linux targets

---

CHANGELOG.md
app/Config.hs
app/Main.hs
hapistrano.cabal
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Core.hs
src/System/Hapistrano/Types.hs
stack.yaml

Currently, when using the `--version` flag, Hapistrano shows the program version and nothing more. This PR includes the Git branch and commit revision, which is handy when developing and having a variety of versions in the PATH.
Example:
```sh
$ hap --version
Hapistrano: 0.3.5.0
branch: version_details
revision: 3442b95d67b49bdfa9ce7a75d1b0e00469b4df2a
```
This PR bumps LTS to 9.20, does a small standardization on the imports style (using stylish-haskell) and a small cleanup.

When showing version information, show also git branch and commit

---

CHANGELOG.md
README.md
app/Main.hs
hapistrano.cabal

Sometimes developers need to deploy a feature branch temporarily, therefore providing ENV interpolation support would make it possible to override values in a configuration file. If a configuration file looks as follows:
```yaml
revision: "_env:HAPISTRANO_REVISION:origin/master"
...
```
The revision could be overridden as follows, during the deployment:
```bash
HAPISTRANO_REVISION=origin/feature_branch stack exec hap -- deploy -c deploy/staging.yaml
```

Add support to interpolate ENV variables in a configuration file

---

CHANGELOG.md
hapistrano.cabal
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Core.hs
stack.yaml

Solves issue #75 
I'm using [process-streaming](https://hackage.haskell.org/package/typed-process) to run a process. 
```
readProcessWithExitCode'
:: ProcessConfig stdin stdoutIgnored stderrIgnored
-> IO (ExitCode, String, String)
readProcessWithExitCode' pc =
SPT.withProcess pc' $ \p -> atomically $
(,,) <$> SPT.waitExitCodeSTM p
<*> return ""
<*> return ""
where
pc' = SPT.setStdout SPT.inherit
$ SPT.setStderr SPT.inherit pc
```
All the magic is in that function ^^. The `readProcessWithExitCode'` method will execute a process but streaming output to `std[out,err]` of its parent (in our case `hap`).
It is good to note that `proc :: FilePath -> [String] -> CreateProcess` sets `std[in,out,err]` to `Inherit` so it will stream the process output to the parent process, also I'm not exactly …

Add process-streaming

---

CHANGELOG.md
hapistrano.cabal

**Why do we need to bump the version?**
Docker Hub only tags a new release after a new tag gets push to GH or after merging a PR in master following the rules describing below:
Therefore the latest changes introduced to the image is only available as `latest` which is why we need to push a new tag:
**TODO**

Bump version from 0.3.9.1 to 0.3.9.2

---

CHANGELOG.md
hapistrano.cabal

I run some tests locally forcing optparse-applicative-0.16.0.0 here are the results:
```diff
resolver: lts-16.9
packages:
- '.'
-
+extra-deps:
+  - optparse-applicative-0.16.0.0
```
Dependencies:
```
➜ stack ls dependencies | grep optparse
optparse-applicative 0.16.0.0
```
Test output:
```
➜ stack test
...
hapistrano> Test suite test passed
```

[#143] Allow optparse-applicative-0.16.0.0

---

.github/workflows/build-and-test.yml
CHANGELOG.md
hapistrano.cabal

- Remove the 7.10.3 job from the CI.
- Update the base version.
- Update the changelog and the version of Hapistrano.

Drop support GHC 7.10.3

---

.github/workflows/build-and-test.yml
README.md
app/Main.hs
example/example.cabal
hapistrano.cabal
spec/System/HapistranoConfigSpec.hs
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Commands/Internal.hs
src/System/Hapistrano/Config.hs
src/System/Hapistrano/Core.hs
src/System/Hapistrano/Types.hs

Hi everyone. After a couple of weeks (and a lot of back and forth and many questions with @CristhianMotoche, thank you!), I have with an implementation for this feature.
This is provided both as a `hap.yaml` boolean option (`keep_one_failed`) as well as a CLI switch option (`--keep-one-failed` or just `-o`). It works as discussed in #154. One thing to note is that the old failed releases get removed before the `keep_releases` option takes place; I think it makes sense since you wouldn't want to accidentally delete failed releases first with `keep_releases` and then remove some others with `keep_one_failed`, which would also leave you with less releases than the amount you specified with `keep_releases`.
Regarding internal changes, there were a bunch of refactors, some of them in the …

Added `keep_one_failed` option that deletes failed releases except for the latest one

---

.github/workflows/build-and-test.yml

I made it so that the step, after echoing the error message, still fails with exit code 1. 
Closes #176.

CI now has an error message for the Haddock step when there are less than 4 modules with 100% documentation

---

.github/workflows/build-and-test.yml

The CI step involving Haddock was displaying:
> **Run # Fixes issue with different haddock coverage with different ghc versions https://github.com/haskell/haddock/issues/123**
after #176, since no name was given to the step. This PR is fixing that.

Added name to Haddock step

---

hapistrano.cabal

Prevents recompilations caused by changes to the `.md` files
```
Run cabal build
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
- hapistrano-0.[4](https://github.com/stackbuilders/hapistrano/runs/5978860261?check_suite_focus=true#step:10:4).3.1 (lib) (file README.md changed)
- hapistrano-0.4.3.1 (test:test) (dependency rebuilt)
- hapistrano-0.4.3.1 (exe:hap) (dependency rebuilt)
```
**Note**
Credits to @jpvillaisaza for suggesting this change.

Move md files to extra-doc-files block

---

CHANGELOG.md
README.md
default.nix
example/example.cabal
hapistrano.cabal
src/System/Hapistrano.hs
src/System/Hapistrano/Commands.hs
src/System/Hapistrano/Commands/Internal.hs
src/System/Hapistrano/Config.hs
src/System/Hapistrano/Core.hs
src/System/Hapistrano/Types.hs

- Avoid 'Table of Contents' in first title to avoid hackage styling issue
- Haddock adds an `id` to the titles parsed from the README.md
- [table-of-contents](https://github.com/haskell/haddock/blob/4411b41aee79fa6365773e4660ca8e3acc6a5b32/haddock-api/resources/html/Linuwial.std-theme/linuwial.css#L80-L87) has some specific styles
- Change titles and add notes for Windows
- Change maintainer and remove it from modules
- I changed the maintainer's email in the cabal file
- I removed the maintainer from the package modules
- Prepare release (v0.5.0.0) since it contains breaking changes. Includes:
- #174
- #183 
- Documentation changes in this PR

[RELEASE] Documentation changes and release preparation

---

CHANGELOG.md
default.nix
hapistrano.cabal

Hapistrano is mainly used as a CLI and its CLI didn't change to request mandatory
field or flags. Therefore, I changed the next version to `0.4.4.0`.

[FIX] Change version to 0.4.4.0

---

app/Main.hs
hapistrano.cabal
spec/System/HapistranoSpec.hs
src/System/Hapistrano.hs

- Include restart command call inside rollback function
- Abstract deploy command into a new function
- This will help to test `deploy` easily since it has been extracted from `app/Main`
- Main becomes easier to read since the Command type constructor take us to the appropriate functions

[NO ISSUE] Refactoring: Move Deploy task into library

---

.github/workflows/build.yml

Current binary caches for GHC don't have ghc902 pacakges for dependencies, and therefore have to be recreated with every build. We could consider a cachix for ourselves to host these, but increasing the timeout should suffice for now, specially since CI minutes are not charged for a public repo.
Fixes https://github.com/stackbuilders/hapistrano/issues/242

Increate timeout for build

---

.envrc
.github/workflows/build.yml
.gitignore
Dockerfile
docs/NIX.md
flake.lock
flake.nix
hapistrano.cabal

This PR simplifies the Nix flake and GHC versions of the flake by removing GHC 8. It also:
- Bumps GHC 9 version from 9.0.2 to 9.6.6 and `transformers` dependency upper bound.
- Changes the GHC-musl image to [the one mentioned here](https://github.com/utdemir/ghc-musl/pull/42#issuecomment-1983312021), since the previous one we were using seems to be unmaintained.
- Adds Cabal, HLint and HLS to the development shell.
- Adds a `.envrc` file for use with `direnv`.
- Updates `flake.lock`.

Simplification of Nix flake and removal of GHC 8

---

.github/workflows/draft.yml
Dockerfile

This PR addresses the following:
- Code cleanup in `Dockerfile` and `draft.yml`
- Introduce new steps in `draft.yml` to compress the binary, change ownership of the file and rename the file afterwards
- Add new step to compress the binary and also download the dependency.

Refactor GitHub Actions draft workflow and Dockerfile to use upx to compress binary
